# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d75f5b1e6ec12f7ef6c96ee6b769edec7744fd91d75fc540fa0e3801ceb0e8947984525348a296516cd0efc05271aa27b7281d7f09e3e490c895e028042ab95

test:
  secret_key_base: d78459d74db08c6661d262957c36b07e2437bc8f24a957c3727bd75dd5a673680c174babf2dc1c9580039f9d9e815c267a2c356b8504dc48d8568a1b343b1ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
